/**
 * @description       : 
 * @author            : Venkatesh Kulkarni
 * @group             : 
 * @last modified on  : 10-07-2023
**/

public with sharing class Constants {

    public static final string NAMED_CRED_CALLOUT  ='callout:';
    public static final string GRANT_TYPE  ='grant_type';
    public static final string SCOPE  ='scope';
    public static final string ERROR  ='error';
    public static final string ACCESS_TOKEN  ='access_token';
    public static final string ERROR_DESCRIPTION  ='error_description';
    public static final string BEARER  ='Bearer';
    public static final string AUTHORIZATION  ='Authorization';
    public static final string UTF_8_ENCODING  ='UTF-8';
    public static final string EQUAL  ='=';
    public static final string AMPERSAND  ='&';
    public static final string VALUE  ='value';
    public static final string EMPTY_STRING  ='';
    public static final string SPACE_STRING  = ' ';
    public static final string CONTENT_TYPE  ='content_type';
    public static final string CLIENT_ID  = 'client_id';
    public static final string CLIENT_SECRET  ='client_secret';
    
}